using System;
using System.Collections.Generic;
using Lua;

namespace Evaluate;

// Registry of pre-baked (source-generated, zero-reflection) Godot bindings.
// The binder consults this before falling back to ambient reflection, so hot
// types pay no reflection cost and are AOT-clean.
public static class Prebaked
{
    private static readonly Dictionary<string, Func<LuaTable>> Bindings = new()
    {
        ["OS"] = OsBinding.Create,        // generated by BindGodotGenerator
    };

    public static bool TryGet(string typeName, out LuaTable table)
    {
        if (Bindings.TryGetValue(typeName, out var make)) { table = make(); return true; }
        table = null!;
        return false;
    }
}
