using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Evaluate.Generator;

// Emits compile-time, reflection-free Lua bindings for a Godot type's public
// static methods. Usage in the consuming project:
//
//   [BindGodot(typeof(Godot.OS))]
//   public partial class OsBinding { }
//
// generates  OsBinding.Create() -> LuaTable  with direct calls like
//   t["GetName"] = new LuaFunction((ctx, ct) => { var r = Godot.OS.GetName(); ctx.Return(r); ... });
//
// Only methods whose whole signature is Lua-convertible (primitives/string) are
// bound — binding others would compile but throw at call time (verifier-caught).
[Generator]
public sealed class BindGodotGenerator : IIncrementalGenerator
{
    private const string AttrName = "Evaluate.BindGodotAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => Build(ctx))
            .Where(static s => s.Source is not null);

        context.RegisterSourceOutput(sources, static (spc, s) =>
            spc.AddSource(s.HintName!, s.Source!));
    }

    private static (string? HintName, string? Source) Build(GeneratorAttributeSyntaxContext ctx)
    {
        var cls = (INamedTypeSymbol)ctx.TargetSymbol;
        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length != 1 ||
            attr.ConstructorArguments[0].Value is not INamedTypeSymbol godotType)
            return (null, null);

        var ns = cls.ContainingNamespace.IsGlobalNamespace ? null : cls.ContainingNamespace.ToDisplayString();
        var godotFqn = godotType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Evaluate pre-baked Godot binding (no runtime reflection)");
        sb.AppendLine("#nullable enable");
        if (ns is not null) sb.AppendLine($"namespace {ns};");
        sb.AppendLine($"partial class {cls.Name}");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Lua.LuaTable Create()");
        sb.AppendLine("    {");
        sb.AppendLine("        var t = new global::Lua.LuaTable();");

        var seen = new System.Collections.Generic.HashSet<string>();
        foreach (var m in godotType.GetMembers().OfType<IMethodSymbol>())
        {
            if (m.DeclaredAccessibility != Accessibility.Public || !m.IsStatic) continue;
            if (m.MethodKind != MethodKind.Ordinary || m.IsGenericMethod) continue;
            if (!m.Parameters.All(p => Kind(p.Type) is not null)) continue;
            if (!(m.ReturnsVoid || Kind(m.ReturnType) is not null)) continue;
            if (!seen.Add(m.Name)) continue;   // first overload per name (MVP)

            EmitMethod(sb, godotFqn, m);
        }

        sb.AppendLine("        return t;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return ($"{cls.Name}.g.cs", sb.ToString());
    }

    private static void EmitMethod(StringBuilder sb, string godotFqn, IMethodSymbol m)
    {
        sb.AppendLine($"        t[\"{m.Name}\"] = new global::Lua.LuaFunction((ctx, ct) =>");
        sb.AppendLine("        {");
        var argNames = new string[m.Parameters.Length];
        for (int i = 0; i < m.Parameters.Length; i++)
        {
            argNames[i] = $"a{i}";
            sb.AppendLine($"            var a{i} = {ReadArg(Kind(m.Parameters[i].Type)!, i)};");
        }
        var call = $"{godotFqn}.{m.Name}({string.Join(", ", argNames)})";
        if (m.ReturnsVoid)
        {
            sb.AppendLine($"            {call};");
            sb.AppendLine("            ctx.Return();");
            sb.AppendLine("            return new global::System.Threading.Tasks.ValueTask<int>(0);");
        }
        else
        {
            sb.AppendLine($"            var __r = {call};");
            sb.AppendLine($"            ctx.Return({ReturnExpr(Kind(m.ReturnType)!, "__r")});");
            sb.AppendLine("            return new global::System.Threading.Tasks.ValueTask<int>(1);");
        }
        sb.AppendLine("        });");
    }

    // Lua reads every number as double; cast to the target width.
    private static string ReadArg(string kind, int i) => kind switch
    {
        "string" => $"ctx.GetArgument<string>({i})",
        "bool" => $"ctx.GetArgument<bool>({i})",
        "double" => $"ctx.GetArgument<double>({i})",
        _ => $"({kind})ctx.GetArgument<double>({i})",   // float/int/long/uint/...
    };

    // LuaValue has implicit conversions from double/bool/string only.
    private static string ReturnExpr(string kind, string v) => kind switch
    {
        "string" or "bool" or "double" => v,
        _ => $"(double){v}",
    };

    private static string? Kind(ITypeSymbol t) => t.SpecialType switch
    {
        SpecialType.System_Boolean => "bool",
        SpecialType.System_String => "string",
        SpecialType.System_Single => "float",
        SpecialType.System_Double => "double",
        SpecialType.System_Int32 => "int",
        SpecialType.System_Int64 => "long",
        SpecialType.System_UInt32 => "uint",
        SpecialType.System_UInt64 => "ulong",
        SpecialType.System_Int16 => "short",
        SpecialType.System_UInt16 => "ushort",
        SpecialType.System_Byte => "byte",
        SpecialType.System_SByte => "sbyte",
        _ => null,
    };
}
