using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Evaluate.Generator;

// Emits compile-time, reflection-free conversion code for every Godot builtin struct
// Variant type (Vector*, Color, Quaternion, Rect2*, Plane, Aabb, Basis, Transform2D/3D,
// Projection, …), discovered from the GodotSharp reference. The consuming codec
// (`[GodotStructCodec] partial class GodotStructCodec`) gets:
//   object? Decompose(Variant)           Variant -> neutral object model
//   Variant Recompose(Variant.Type, obj) neutral object model -> Variant
//   Variant.Type? TypeByName(string)     `_type` name -> Variant.Type
//   bool IsStruct(Variant.Type)
// A new Godot builtin is picked up automatically — no hand edits, no runtime reflection.
[Generator]
public sealed class StructCodecGenerator : IIncrementalGenerator
{
    private const string AttrName = "Evaluate.GodotStructCodecAttribute";

    // Variant struct types we do NOT decompose (handled elsewhere / not value data).
    private static readonly HashSet<string> Excluded = new() { "Rid", "Callable", "Signal", "Object", "Nil" };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => Build((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation))
            .Where(static s => s.Source is not null);

        context.RegisterSourceOutput(sources, static (spc, s) => spc.AddSource(s.HintName!, s.Source!));
    }

    private sealed class Comp
    {
        public string Member = "";     // accessor on the struct value (field/prop name)
        public string Key = "";        // lower-case key used in the `_type` table
        public ITypeSymbol Type = null!;
    }

    private static (string? HintName, string? Source) Build(INamedTypeSymbol cls, Compilation comp)
    {
        var variant = comp.GetTypeByMetadataName("Godot.Variant");
        var typeEnum = variant?.GetTypeMembers("Type").FirstOrDefault();
        if (typeEnum is null) return (null, null);

        // Discover the struct Variant types from the Variant.Type enum: each member whose
        // `Godot.<Name>` resolves to a struct (and isn't excluded or a packed array).
        var structs = new List<(string Name, INamedTypeSymbol Sym)>();
        var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var f in typeEnum.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsConst))
        {
            var name = f.Name;
            if (Excluded.Contains(name) || name.StartsWith("Packed")) continue;
            if (comp.GetTypeByMetadataName("Godot." + name) is { TypeKind: TypeKind.Struct } s)
            {
                structs.Add((name, s));
                set.Add(s);
            }
        }
        if (structs.Count == 0) return (null, null);

        bool IsScalar(ITypeSymbol t) => t.SpecialType is
            SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Int32
            or SpecialType.System_Int64 or SpecialType.System_Byte;
        string Cast(ITypeSymbol t) => t.SpecialType switch
        {
            SpecialType.System_Single => "(float)",
            SpecialType.System_Double => "",
            SpecialType.System_Int32 => "(int)",
            SpecialType.System_Int64 => "(long)",
            SpecialType.System_Byte => "(byte)",
            _ => "",
        };

        // Component layout for a struct: its public settable fields (field mode), else the
        // members matched to the largest name-matching constructor (ctor mode).
        List<Comp> FieldComps(INamedTypeSymbol s) => s.GetMembers().OfType<IFieldSymbol>()
            .Where(m => m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic
                        && !m.IsConst && !m.IsReadOnly && !m.IsImplicitlyDeclared)
            .Select(m => new Comp { Member = m.Name, Key = m.Name.ToLowerInvariant(), Type = m.Type })
            .ToList();

        IMethodSymbol? CtorFor(INamedTypeSymbol s, Dictionary<string, (string Name, ITypeSymbol Type)> readable) =>
            s.InstanceConstructors
                .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
                .Where(c => c.Parameters.All(p => readable.ContainsKey(p.Name.ToLowerInvariant())))
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Evaluate Godot struct codec (no runtime reflection)");
        sb.AppendLine("#nullable enable");
        var ns = cls.ContainingNamespace.IsGlobalNamespace ? null : cls.ContainingNamespace.ToDisplayString();
        if (ns is not null) sb.AppendLine($"namespace {ns};");
        sb.AppendLine($"static partial class {cls.Name}");
        sb.AppendLine("{");

        var ctorMode = new HashSet<string>();   // names built via constructor (not default+set)
        var compsByName = new Dictionary<string, List<Comp>>();

        foreach (var (name, s) in structs)
        {
            var fields = FieldComps(s);
            List<Comp> comps;
            bool useCtor = fields.Count == 0;
            if (useCtor)
            {
                var readable = new Dictionary<string, (string, ITypeSymbol)>();
                foreach (var m in s.GetMembers())
                {
                    if (m is IFieldSymbol fs && fs.DeclaredAccessibility == Accessibility.Public && !fs.IsStatic)
                        readable[fs.Name.ToLowerInvariant()] = (fs.Name, fs.Type);
                    else if (m is IPropertySymbol ps && ps.DeclaredAccessibility == Accessibility.Public
                             && !ps.IsStatic && ps.GetMethod is not null && ps.Parameters.Length == 0)
                        readable[ps.Name.ToLowerInvariant()] = (ps.Name, ps.Type);
                }
                var ctor = CtorFor(s, readable);
                if (ctor is null) continue;   // can't reconstruct generically — skip
                ctorMode.Add(name);
                comps = ctor.Parameters.Select(p =>
                {
                    var (mem, ty) = readable[p.Name.ToLowerInvariant()];
                    return new Comp { Member = mem, Key = mem.ToLowerInvariant(), Type = ty };
                }).ToList();
            }
            else comps = fields;

            compsByName[name] = comps;
            bool allScalar = comps.All(c => IsScalar(c.Type));

            // ---- Decompose<Name> ----
            sb.Append($"    internal static object Decompose{name}(global::Godot.{name} v) => ");
            if (allScalar)
                sb.AppendLine($"Scalars({string.Join(", ", comps.Select(c => $"(double)v.{c.Member}"))});");
            else
            {
                var fieldsTxt = comps.Select(c => IsScalar(c.Type)
                    ? $"(\"{c.Key}\", (object)(double)v.{c.Member})"
                    : $"(\"{c.Key}\", (object)Decompose{StructName(set, c.Type)}(v.{c.Member}))");
                sb.AppendLine($"Table(\"{name}\", {string.Join(", ", fieldsTxt)});");
            }

            // ---- Recompose<Name> ----
            sb.AppendLine($"    internal static global::Godot.{name} Recompose{name}(object r)");
            sb.AppendLine("    {");
            string Read(Comp c, int i) => IsScalar(c.Type)
                ? $"{Cast(c.Type)}Num(Field(r, \"{c.Key}\", {i}))"
                : $"Recompose{StructName(set, c.Type)}(Field(r, \"{c.Key}\", {i}))";
            if (useCtor)
                sb.AppendLine($"        return new global::Godot.{name}({string.Join(", ", comps.Select(Read))});");
            else
            {
                sb.AppendLine($"        var s = default(global::Godot.{name});");
                for (int i = 0; i < comps.Count; i++)
                    sb.AppendLine($"        s.{comps[i].Member} = {Read(comps[i], i)};");
                sb.AppendLine("        return s;");
            }
            sb.AppendLine("    }");
        }

        // ---- dispatch ----
        sb.AppendLine("    internal static object? Decompose(global::Godot.Variant v) => v.VariantType switch");
        sb.AppendLine("    {");
        foreach (var (name, _) in structs.Where(x => compsByName.ContainsKey(x.Name)))
            sb.AppendLine($"        global::Godot.Variant.Type.{name} => Decompose{name}(v.As{name}()),");
        sb.AppendLine("        _ => null,");
        sb.AppendLine("    };");

        sb.AppendLine("    internal static global::Godot.Variant Recompose(global::Godot.Variant.Type t, object r) => t switch");
        sb.AppendLine("    {");
        foreach (var (name, _) in structs.Where(x => compsByName.ContainsKey(x.Name)))
            sb.AppendLine($"        global::Godot.Variant.Type.{name} => Recompose{name}(r),");
        sb.AppendLine("        _ => default,");
        sb.AppendLine("    };");

        sb.AppendLine("    internal static global::Godot.Variant.Type? TypeByName(string name) => name.ToLowerInvariant() switch");
        sb.AppendLine("    {");
        foreach (var (name, _) in structs.Where(x => compsByName.ContainsKey(x.Name)))
            sb.AppendLine($"        \"{name.ToLowerInvariant()}\" => global::Godot.Variant.Type.{name},");
        sb.AppendLine("        _ => (global::Godot.Variant.Type?)null,");
        sb.AppendLine("    };");

        sb.AppendLine("    internal static bool IsStruct(global::Godot.Variant.Type t) => t switch");
        sb.AppendLine("    {");
        foreach (var (name, _) in structs.Where(x => compsByName.ContainsKey(x.Name)))
            sb.AppendLine($"        global::Godot.Variant.Type.{name} => true,");
        sb.AppendLine("        _ => false,");
        sb.AppendLine("    };");

        sb.AppendLine("}");
        return ($"{cls.Name}.Codec.g.cs", sb.ToString());
    }

    // The generated method suffix for a component's struct type (its simple name).
    private static string StructName(HashSet<INamedTypeSymbol> set, ITypeSymbol t) => t.Name;
}
